version: "2.0"
type: node-port
services:
  vm:
    image: filswan/ubuntu-ssh-user:22.04
    env:
      - sshkey=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9lbSSmLSznWZQ5q7f/OqumtXaM/x6sLWubl4Ro2qWbHLrwXGnpvY/IlCREV1vEmjiDlIilYgg6SEr3mFtPP4CPsedn9SkreWrDxoQClA7l6+OdIRHbvMa/kBgby0Bjwq+Kd4pE2s2x4rSqww6V/gL7D+4PikN+LDBTaXr8Go0jOglcgP1ZLuKAZIU3G0g81bEiTm59Oakc7AfVYnvR+QeeMwW27mVK/4aN7NsZT4l3E0Gj2dB61367ypEswrLaAzrhZmqIMZZxWo1wi+5IVyEqnn4dhsIY7iCDe4DknnnEWUYO4A/Rbfz9xnh9m0UVpJyVZjB+DcAPMzrVMNvGjgQh6WJ10Y2h8GeCWRuIYmxHVxwtHoH+fl0syE0ZO+SNXKk1p6VYFPMs4ZBrwn8xdtfZIU7JReZOfP5IjhhJfanQqNOKNYqMQgF6HRF4u85w9mPqGps4NCDgDtC1xIsNZIF+asmJ9eX4l8ZxO7Lw7CC3Ju5eTXG7myIaAoq8mOp/Zc= aaa@LAPTOP-F9AOI0BQ
      - username=u01
    expose:
        - port: 22
        - port: 30002
        - port: 30003
        - port: 30004
        - port: 30005
        - port: 30006
        - port: 30007
        - port: 30008
deployment:
  vm:
    lagrange:
      count: 1
