version: "2.0"
type: node-port
services:
  vm:
    image: filswan/ubuntu-ssh-user:22.04
    env:
      - sshkey=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5yeadyISi2hBG+DBTZ6AdpFraox69EqqAPhdSEp0V+z4N7RNzdDbr/qahOHow1XUC8Ayv90GMI+CyhM3WGs6MH46TR4UBEAu8kIBRLVoxNrzBPoEdjFy9qQvclqRdQEaSRSXPXJSuxPC1gqQ2+y86HR2d3EzClcFo37975xPtrmeeifH2svLsl48OSf64piOSLi5gVmSIX1+xVhhm05wS02CPe5TpGJ5nYzfUihunVx8Cvd1wXg1dSxskJZIDqnwdkshtczETLA5Iu1FtbwMgdoRkGHdg6xRCHNWC75ZRHCukQAbSuhM7e3enJOwCyrRDcOXNgAGBzPjwTFRy6Fj5mBVLV2pxyQNgfS8p4UYJvCjCiUvksxaMMoLnjn/AMponbj6h/UcNDb2smihCVW07FIMe6hz5YVHopsHp+0DFHKOhFMnOQJ2w9yAHoOHUHbufrYTCTLv/zbMRgH7qbr1G3zI7kuoXfLv73byexgsQq3j9LlFzXgreZssg7uZUD0s= aaa@LAPTOP-F9AOI0BQ
      - username=u01
    expose:
        - port: 22
        - port: 30032
        - port: 30033
        - port: 30034
        - port: 30035
        - port: 30036
        - port: 30037
        - port: 30038
deployment:
  vm:
    lagrange:
      count: 1
